Clean-up guest builds
risc0/zeth pull request #62
Opened 2023-11-30 11:53 UTC by capossele

As the `[target.'cfg(not(target_os = "zkvm"))'.dependencies]` does not seem to work for some reason, this PR exposes the feature `host` to prevent unnecessary deps ending up in the guest builds

2023-11-30 15:38 UTC, Wollac requested changes
Looking at the `Cargo.lock` it seems to work, but I do not understand the details:
- The TOML still contains `[target.'cfg(not(target_os = "zkvm"))'.dependencies]`. So this is still needed, but simply adding the optional will do the trick?
- Building the lib with `--no-default-features` now fails because the target OS is not `zkvm`, but all those dependencies are not included. This also causes problems with the rust-analyzer. Is there a way to fix this? One alternative I could think of is to remove all `#[cfg(not(target_os = "zkvm"))]` and manually enable/disable the `host` feature. However, I am not sure if this is a good idea.

2023-11-30 15:52 UTC, Wollac commented on lib/Cargo.toml
> +]
`cargo sort` adds a trailing newline.

2023-11-30 16:12 UTC, capossele commented
Yeah I'm not sure why `[target.'cfg(not(target_os = "zkvm"))'.dependencies]` does not really work as expected. It can be removed though if properly switching as you suggested from `#[cfg(not(target_os = "zkvm"))]` to #[cfg(feature = "host"))].
I've pushed a commit doing that.

Overall this is just a suggestion, maybe a bit hacky, so no harm in closing it if you guys are not convinced. Obviously would be better to understand why `[target.'cfg(not(target_os = "zkvm"))'.dependencies]` does not properly work

2023-11-30 17:44 UTC, capossele commented
Actually I did not feel comfortable at removing the `#[cfg(not(target_os = "zkvm"))]`. So I ended up having them both

2023-12-12 14:29 UTC, Wollac commented
It seems that `[target.'cfg(not(target_os = "zkvm"))'.dependencies]` actually works as expected, but the disabled dependencies show up in the `Cargo.lock` of the guest. However, they are resolved correctly. See: https://github.com/rust-lang/cargo/issues/10801

2023-12-12 14:29 UTC, closed without merging